import { radius } from '../foundations/radius';

export const feedCardTokens = {
  minHeight: 607,
  paidMinHeight: 563,
  width: 393,
  radius: radius.sm,
  paddingHorizontal: 16,
  paddingVertical: 12,
  sectionGap: 16,
  headerHeight: 40,
  headerGap: 12,
  avatarSize: 40,
  mediaHeight: 393,
  mediaGap: 8,
  contentGap: 8,
  contentPaddingTop: 0,
  previewCollapsedHeight: 40,
  previewOverlayWidth: 120,
  previewFadeWidth: 20,
  previewButtonWidth: 100,
  previewButtonHeight: 20,
  actionRowHeight: 36,
  actionRowGap: 8,
  fullBleedOffset: 16,
  skeletonRadius: 22,
  skeletonTextWidth: 120,
  skeletonTitleWidth: 164,
  skeletonButtonWidth: 64,
  paywallIconBoxSize: 42,
  paywallIconBoxRadius: 10,
  paywallIconInnerSize: 30,
  paywallButtonWidth: 239,
  paywallMessageContainerWidth: 393,
  paywallMessageContainerPaddingHorizontal: 16,
  paywallMessageContainerHeight: 157,
  paywallMessageWidth: 236,
  paywallContentWidth: 260,
  paywallContentHeight: 114,
  paywallContentGap: 12,
  paywallTextIconHeight: 90,
} as const;
